### ISSUE TITLE
Add attribution information (from atom or bond index) for the items highlighted in the svg

### ISSUE THREAD

**Issue by ShangChien** [MichelML/rdkit-js#71]
### **Add attribution information (from atom or bond index) for  the elements highlighted in the svg, this will be helpful for further coding**
I super like the encoding and display format of svg, and I want to add some web interaction (click, doubleclick) to the 2D molecular graph generated by rdkit.js. 
_eg: Click on an atom or chemical bond to highlight it, means it is selected. Then return the index of the selected atom or chemical bond to the backend, and do further computationally intensive tasks in the backend._

**I simply implemented the above idea through a series of svg native methods.**
![2022-04-06 110634](https://user-images.githubusercontent.com/48350636/161888176-2607e684-5b54-4e51-83eb-843c463013e6.png)
Put the highlight on top and add transparency. Click to change color, and return to index. But the current rdkitjs natively highlighted information does not have its index. This is the problem I meet. 

###suggestion

My solution is map coordinates of the highlight  and atom and bond，to find the smallest distance difference and get the solid item's index. **BUT Map operation consumes performance** 

I think the ideal way is that When rdkit returns the svg, providing the index as the solid item, for each highlighted item.
(like:  index information contained in the class as shown in the figure below)
![2022-04-06 113306](https://user-images.githubusercontent.com/48350636/161890673-d52d8a85-17cc-4dda-8442-f2d1f939a3d9.png)

**Comment by MichelML** [comment]
Thank you @ShangChien , I would recommend you to log this very great suggestion as a discussion question on the main rdkit repo https://github.com/rdkit/rdkit/discussions  

I know it might seems a bit confusing for now, but this repository is meant to be dedicated to "what sits on top" of the core rdkit minimal lib for javascript library. The core features that should be added to the wasm module should be logged/requested in the core rdkit repository.

That being said, I personally think your suggestion is great to be able to add interactivity in a very granular and clean way.

cc @greglandrum @ptosco @DavidACosgrove

**Comment by ShangChien** [comment]
> Thank you @ShangChien , I would recommend you to log this great suggestion as a discussion question on the main rdkit repo https://github.com/rdkit/rdkit/discussions

> cc @greglandrum @ptosco @DavidACosgrove

Thank you very much！ @MichelML ， I will do it.
